export const SAVE_SECTION = 'SAVE_SECTIONS';
export const SAVE_SECTION_ERROR = 'SAVE_SECTION_ERROR';

export const GET_SECTIONS = 'GET_SECTIONS';
export const GET_SECTIONS_ERROR = 'GET_SECTIONS_ERROR';
